eureka:
  client:
    register-with-eureka: false
server:
  port: 8222

spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: interactions
          uri: http://localhost:8070
          predicates:
            - Path=/api/v1/interactions/**
          filters:
            - AuthenticationFilter

        - id: comments
          uri: http://localhost:8070
          predicates:
            - Path=/api/v1/comments/**
          filters:
            - AuthenticationFilter

        - id: shareds
          uri: http://localhost:8070
          predicates:
            - Path=/api/v1/shareds/**
          filters:
            - AuthenticationFilter

        - id: reactions
          uri: http://localhost:8070
          predicates:
            - Path=/api/v1/reactions/**
          filters:
            - AuthenticationFilter

        - id: users-auth
          uri: http://localhost:8101
          predicates:
            - Path=/api/v1/auth/**


        - id: users-data
          uri: http://localhost:8083
          predicates:
            - Path=/api/v1/users/**
          filters:
            - AuthenticationFilter

        - id: medias
          uri: http://localhost:8016
          predicates:
            - Path=/api/v1/medias/**
          filters:
            - AuthenticationFilter

        - id: friend-services
          uri: http://localhost:8078
          predicates:
            - Path=/api/friend/**
          filters:
            - AuthenticationFilter

        - id: post-services
          uri: http://localhost:8074
          predicates:
            - Path=/api/v1/post/**
          filters:
            - AuthenticationFilter
#/api/friend-requests
    discovery:
      enabled: true
    config:
      enabled: false


management:
  tracing:
    sampling:
      probability: 1.0



